### ISSUE TITLE
Installation fails in branch master

### ISSUE THREAD

**Issue by axl89** [articaST/integriaims#2]
When importing the **integria_db.sql** file into the database you get:

`ERROR 1064 (42000) at line 1351: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FOREIGN KEY (`id_folder`) REFERENCES tfolder_report(`id`)`

**Comment by m-lopez-f** [comment]
Your pull request have was include in repo and fixed this problem.
